# Generated by Django 4.2.3 on 2023-07-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=120, verbose_name='Email Address')),
                ('number', models.CharField(max_length=20, verbose_name='Client Number')),
                ('name', models.CharField(max_length=120, verbose_name='Client Name')),
                ('message', models.CharField(max_length=120, verbose_name='Client Message')),
            ],
        ),
    ]
